// src/lib/validation/issueMetaEtsy.ts

import type { IssueMetaMap } from "./issueMeta";

export const ETSY_ISSUE_META: IssueMetaMap = {
  "etsy/missing_required_header": {
    code: "etsy/missing_required_header",
    title: "Missing required column",
    explanation: "Your CSV is missing one or more required Etsy columns for this template.",
    whyPlatformCares: "Etsy’s bulk tools require specific columns to identify listings and apply changes. Missing columns can cause rows to be rejected or edits to be applied incorrectly.",
    howToFix: "Compare your headers to the Etsy template for this mode and add the missing column(s). You can also re-download the StriveFormats Etsy template and paste your data into it.",
    category: "structure",
    blocking: true,
    autoFixable: false,
  },
  "etsy/missing_title": {
    code: "etsy/missing_title",
    title: "Missing title",
    explanation: "A listing title is blank.",
    whyPlatformCares: "Etsy requires a title for listings. Blank titles can prevent a listing from being created or updated correctly.",
    howToFix: "Fill in the Title field for this row.",
    category: "seo",
    blocking: true,
    autoFixable: false,
  },
  "etsy/title_too_long": {
    code: "etsy/title_too_long",
    title: "Title too long",
    explanation: "The title exceeds Etsy’s maximum length.",
    whyPlatformCares: "Over-long titles may be rejected or truncated by Etsy, reducing search quality.",
    howToFix: "Shorten the title to fit Etsy’s limit (recommended ≤ 140 characters).",
    category: "seo",
    blocking: false,
    autoFixable: false,
  },
  "etsy/missing_price": {
    code: "etsy/missing_price",
    title: "Missing price",
    explanation: "Price is blank.",
    whyPlatformCares: "Etsy requires a valid price for purchasable listings. Missing prices can cause import errors.",
    howToFix: "Enter a numeric price (e.g., 19.99).",
    category: "pricing",
    blocking: true,
    autoFixable: false,
  },
  "etsy/invalid_price": {
    code: "etsy/invalid_price",
    title: "Invalid price",
    explanation: "Price is not a valid number.",
    whyPlatformCares: "Etsy rejects prices that are not valid numeric values.",
    howToFix: "Use a numeric value with an optional decimal (e.g., 19.99). Remove currency symbols.",
    category: "pricing",
    blocking: true,
    autoFixable: false,
  },
  "etsy/invalid_quantity": {
    code: "etsy/invalid_quantity",
    title: "Invalid quantity",
    explanation: "Quantity is not a valid whole number.",
    whyPlatformCares: "Etsy requires whole-number inventory counts. Invalid quantities can cause row rejection.",
    howToFix: "Use a whole number (e.g., 0, 1, 25).",
    category: "inventory",
    blocking: true,
    autoFixable: false,
  },
  "etsy/too_many_tags": {
    code: "etsy/too_many_tags",
    title: "Too many tags",
    explanation: "This row has more tags than Etsy allows.",
    whyPlatformCares: "Etsy limits tag count; extra tags are ignored and can reduce listing quality.",
    howToFix: "Reduce to the allowed number of tags (commonly up to 13).",
    category: "seo",
    blocking: false,
    autoFixable: false,
  },
  "etsy/tag_too_long": {
    code: "etsy/tag_too_long",
    title: "Tag too long",
    explanation: "A tag exceeds Etsy’s maximum length.",
    whyPlatformCares: "Over-long tags may be ignored by Etsy.",
    howToFix: "Shorten each tag (commonly ≤ 20 characters per tag).",
    category: "seo",
    blocking: false,
    autoFixable: false,
  },
  "etsy/invalid_image_url": {
    code: "etsy/invalid_image_url",
    title: "Invalid image URL",
    explanation: "One or more image URLs don’t look like valid http(s) links.",
    whyPlatformCares: "Broken image URLs can cause listing image imports to fail.",
    howToFix: "Ensure each image URL starts with http:// or https:// and is separated using the expected delimiter for this template.",
    category: "images",
    blocking: false,
    autoFixable: true,
  },
  "etsy/invalid_currency": {
    code: "etsy/invalid_currency",
    title: "Invalid currency",
    explanation: "Currency code is not a valid 3-letter currency code.",
    whyPlatformCares: "Etsy expects valid currency codes when provided; invalid codes may be rejected or ignored.",
    howToFix: "Use a 3-letter ISO currency code (e.g., USD, CAD, GBP) or leave it blank if the template doesn’t require it.",
    category: "pricing",
    blocking: false,
    autoFixable: false,
  },
};
