// src/lib/validation/issueMetaWooCommerce.ts

import type { IssueMetaMap } from "./issueMeta";

export const WOO_ISSUE_META: IssueMetaMap = {
  "woocommerce/missing_required_header": {
    code: "woocommerce/missing_required_header",
    title: "Missing required column",
    explanation: "Your CSV is missing one or more required WooCommerce columns for this template.",
    whyPlatformCares: "WooCommerce’s importer maps by column name. Missing required columns can prevent products/variations from being created or updated correctly.",
    howToFix: "Add the missing header(s) or re-download the StriveFormats WooCommerce template and paste your data into it.",
    category: "structure",
    blocking: true,
    autoFixable: false,
  },
  "woocommerce/invalid_type": {
    code: "woocommerce/invalid_type",
    title: "Invalid product type",
    explanation: "Type is not recognized as a valid WooCommerce product type.",
    whyPlatformCares: "WooCommerce uses the Type field to decide how to interpret the row (simple/variable/variation). Invalid types can break the import.",
    howToFix: "Use a valid type like simple, variable, or variation.",
    category: "structure",
    blocking: true,
    autoFixable: false,
  },
  "woocommerce/missing_name": {
    code: "woocommerce/missing_name",
    title: "Missing product name",
    explanation: "Name is blank for a product row.",
    whyPlatformCares: "WooCommerce requires a product name for new products and often for updates depending on importer settings.",
    howToFix: "Fill in the Name column for this row.",
    category: "seo",
    blocking: true,
    autoFixable: false,
  },
  "woocommerce/variation_missing_parent": {
    code: "woocommerce/variation_missing_parent",
    title: "Variation missing parent linkage",
    explanation: "A variation row isn’t linked to a parent variable product.",
    whyPlatformCares: "WooCommerce requires each variation to reference its parent (typically via Parent or Parent SKU/ID depending on template). Unlinked variations are rejected.",
    howToFix: "Set the Parent/Parent SKU (or the required parent reference) so the variation points to an existing variable product.",
    category: "variant",
    blocking: true,
    autoFixable: false,
  },
  "woocommerce/variation_missing_attributes": {
    code: "woocommerce/variation_missing_attributes",
    title: "Variation missing attributes",
    explanation: "A variation row is missing one or more attribute values required to define the variation.",
    whyPlatformCares: "Variations must have attribute values (e.g., Size=Small) to be uniquely identified and imported correctly.",
    howToFix: "Fill in the attribute columns for this variation (e.g., Attributes or Attribute 1 name/value fields depending on your template).",
    category: "variant",
    blocking: true,
    autoFixable: false,
  },
  "woocommerce/duplicate_variation_combo": {
    code: "woocommerce/duplicate_variation_combo",
    title: "Duplicate variation combination",
    explanation: "Multiple variation rows share the same parent + attribute combination.",
    whyPlatformCares: "Duplicate variation combinations can cause WooCommerce to overwrite data or create unpredictable results during import.",
    howToFix: "Ensure each variation under a parent has a unique set of attribute values (e.g., Size/Color combination).",
    category: "variant",
    blocking: false,
    autoFixable: false,
  },
  "woocommerce/invalid_price": {
    code: "woocommerce/invalid_price",
    title: "Invalid price",
    explanation: "Price is not a valid number.",
    whyPlatformCares: "WooCommerce rejects invalid numeric values for price fields.",
    howToFix: "Use a numeric value (e.g., 19.99). Remove currency symbols and commas.",
    category: "pricing",
    blocking: true,
    autoFixable: false,
  },
  "woocommerce/invalid_int": {
    code: "woocommerce/invalid_int",
    title: "Invalid integer",
    explanation: "A field expected to be a whole number contains an invalid value.",
    whyPlatformCares: "WooCommerce expects whole numbers for fields like stock quantity. Invalid values can cause import failures.",
    howToFix: "Use a whole number (e.g., 0, 5, 120).",
    category: "inventory",
    blocking: true,
    autoFixable: false,
  },
  "woocommerce/invalid_bool": {
    code: "woocommerce/invalid_bool",
    title: "Invalid boolean value",
    explanation: "A boolean field contains an unexpected value.",
    whyPlatformCares: "WooCommerce expects common boolean values (yes/no, true/false, 1/0). Invalid booleans may be ignored or misread.",
    howToFix: "Use yes/no or true/false (or 1/0) based on the template.",
    category: "structure",
    blocking: false,
    autoFixable: true,
  },
  "woocommerce/invalid_visibility": {
    code: "woocommerce/invalid_visibility",
    title: "Invalid catalog visibility",
    explanation: "Catalog visibility value is not recognized.",
    whyPlatformCares: "WooCommerce uses catalog visibility to decide where products appear. Invalid values may be ignored.",
    howToFix: "Use one of: visible, catalog, search, hidden.",
    category: "seo",
    blocking: false,
    autoFixable: false,
  },
  "woocommerce/invalid_image_url": {
    code: "woocommerce/invalid_image_url",
    title: "Invalid image URL",
    explanation: "One or more image URLs don’t look like valid http(s) links.",
    whyPlatformCares: "Invalid image URLs can cause product image imports to fail.",
    howToFix: "Ensure each image URL starts with http:// or https:// and uses the expected delimiter (often comma).",
    category: "images",
    blocking: false,
    autoFixable: true,
  },
};
